import { generateUId } from "./helpers";

export const CATELOG_FIELDS = [
  {
    category: "Input",
    name: "input",
    label: "Input",
    type: "text",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    // dependent: false,

    encode: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "Number",
    name: "number",
    label: "Number",
    type: "number",
    dataType: "Int",
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "Int",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "TextArea",
    name: "text_area",
    label: "Text Area",
    type: "textarea",
    readOnly: false,
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "PlainText",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "AutoIncrement",
    name: "auto_increment",
    label: "Auto Increment",
    type: "text",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: true,
    prependText: "",
    unique: true,
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "Password",
    name: "password",
    label: "Password",
    type: "password",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "Date",
    name: "date",
    label: "Date",
    type: "date",
    dataType: "DATETIME",
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "Date",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "Radio",
    name: "radio",
    label: "Radio",
    type: "radio",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Manual",

    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    options: [
      {
        optionId: generateUId(),
        label: "Radio 1",
        active: true,
        default: false,
        collapsed: true,
      },
      {
        optionId: generateUId(),
        label: "Radio 2",
        active: true,
        default: false,
        collapsed: true,
      },
    ],
  },
  {
    category: "Checkbox",
    name: "checkbox",
    label: "Checkbox",
    type: "checkbox",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Manual",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    options: [
      {
        optionId: generateUId(),
        label: "Checkbox 1",
        active: true,
        default: false,
        collapsed: true,
      },
      {
        optionId: generateUId(),
        label: "Checkbox 2",
        active: true,
        default: false,
        collapsed: true,
      },
    ],
  },
  {
    category: "DropDown",
    name: "dropdown",
    label: "DropDown",
    type: "select",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Manual",
    variant: "Single",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    options: [
      {
        optionId: generateUId(),
        label: "DropDown 1",
        active: true,
        default: false,
        collapsed: true,
      },
      {
        optionId: generateUId(),
        label: "DropDown 2",
        active: true,
        default: false,
        collapsed: true,
      },
    ],
  },
  {
    category: "Reference",
    name: "reference",
    label: "Reference",
    type: "reference",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "Dropdown",
    dataSourceType: "Dynamic",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "Lookup",
    name: "lookup",
    label: "Lookup",
    type: "lookup",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Dynamic",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },

  {
    category: "Json",
    name: "json",
    label: "Json",
    type: "json",
    dataType: "longtext",
    length: 0,
    mandatory: false,
    hidden: false,
    audit: false,
    // variant:null,
    dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "Switch",
    name: "switch",
    label: "Toggle Switch",
    type: "switch",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    options: [
      {
        optionId: generateUId(),
        label: "Yes",
        active: true,
        default: false,
        value: true,
        collapsed: true,
      },
      {
        optionId: generateUId(),
        label: "No",
        active: true,
        default: false,
        value: false,
        collapsed: true,
      },
    ],
    dataSourceType: "Manual",
    // dependent: false,
    showLabel: true,
  },
  {
    category: "Attachment",
    name: "attachment",
    label: "Attachment",
    type: "file",
    dataType: "Blob",
    mandatory: false,
    hidden: false,
    audit: false,
    dependent: false,
  },
];

export const FIELDS = [
  {
    category: "Input",
    name: "input",
    label: "Input",
    type: "text",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    // dependent: false,

    encode: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "Number",
    name: "number",
    label: "Number",
    type: "number",
    dataType: "Int",
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "Int",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "TextArea",
    name: "text_area",
    label: "Text Area",
    type: "textarea",
    readOnly: false,
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "PlainText",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "AutoIncrement",
    name: "auto_increment",
    label: "Auto Increment",
    type: "text",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: true,
    prependText: "",
    unique: true,
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "Password",
    name: "password",
    label: "Password",
    type: "password",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "Date",
    name: "date",
    label: "Date",
    type: "date",
    dataType: "DATETIME",
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "Date",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "Radio",
    name: "radio",
    label: "Radio",
    type: "radio",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Manual",

    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
    options: [
      {
        optionId: generateUId(),
        label: "Radio 1",
        active: true,
        default: false,
        collapsed: true,
      },
      {
        optionId: generateUId(),
        label: "Radio 2",
        active: true,
        default: false,
        collapsed: true,
      },
    ],
  },

  {
    category: "Checkbox",
    name: "checkbox",
    label: "Checkbox",
    type: "checkbox",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Manual",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
    options: [
      {
        optionId: generateUId(),
        label: "Checkbox 1",
        active: true,
        default: false,
        collapsed: true,
      },
      {
        optionId: generateUId(),
        label: "Checkbox 2",
        active: true,
        default: false,
        collapsed: true,
      },
    ],
  },
  {
    category: "DropDown",
    name: "dropdown",
    label: "DropDown",
    type: "select",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Manual",
    variant: "Single",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
    options: [
      {
        optionId: generateUId(),
        label: "DropDown 1",
        active: true,
        default: false,
        collapsed: true,
      },
      {
        optionId: generateUId(),
        label: "DropDown 2",
        active: true,
        default: false,
        collapsed: true,
      },
    ],
  },
  {
    category: "Reference",
    name: "reference",
    label: "Reference",
    type: "reference",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "Dropdown",
    dataSourceType: "Dynamic",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "Lookup",
    name: "lookup",
    label: "Lookup",
    type: "lookup",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Dynamic",
    // dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "ModuleForm",
    name: "moduleform",
    label: "ModuleForm",
    type: "moduleform",
    dataType: "Varchar",
    length: 500,
    mandatory: false,
    hidden: false,
    audit: false,
    variant: "Module",
    dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
  },
  {
    category: "TableReference",
    name: "reference_table",
    label: "Reference Table",
    type: "table-reference",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    highlightInitialCharacter: false,
    dataSourceType: "Dynamic",
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
    variant: "Table",
    sortBy: "created_at",
  },
  {
    category: "TableLookup",
    name: "lookup_table",
    label: "Lookup Table",
    type: "table-lookup",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Dynamic",
    dependent: false,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "activity",
    name: "activity",
    label: "Activity",
    type: "activity",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    dataSourceType: "Dynamic",
    dependent: false,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "Json",
    name: "json",
    label: "Json",
    type: "json",
    dataType: "longtext",
    length: 0,
    mandatory: false,
    hidden: false,
    audit: false,
    // variant:null,
    dependent: false,
    showLabel: true,
    globalSearch: false,
    showTimePeriod: false,
    activityReferenceField: false,
    enableFilterPanel: false,
    showInMinimalView: false,
    showInNewRecord: true,
    defaultLabel: false,
    editable: true,
  },
  {
    category: "Switch",
    name: "switch",
    label: "Toggle Switch",
    type: "switch",
    dataType: "Varchar",
    length: 56,
    mandatory: false,
    hidden: false,
    audit: false,
    options: [
      {
        optionId: generateUId(),
        label: "Yes",
        active: true,
        default: false,
        value: true,
        collapsed: true,
      },
      {
        optionId: generateUId(),
        label: "No",
        active: true,
        default: false,
        value: false,
        collapsed: true,
      },
    ],
    dataSourceType: "Manual",
    // dependent: false,
    showLabel: true,
  },
];

export const variants = {
  Number: [
    {
      label: "Non Decimal",
      name: "Int",
    },
    {
      label: "Decimal",
      name: "Float",
    },
  ],
  DropDown: [
    {
      label: "Single Value",
      name: "Single",
    },
    {
      label: "Multiple Values",
      name: "Multiple",
    },
  ],
  TextArea: [
    {
      label: "Plain Text",
      name: "PlainText",
    },
    {
      label: "Rich Text",
      name: "RichText",
    },
  ],
  Reference: [
    {
      label: "Dropdown",
      name: "Dropdown",
    },
    {
      label: "Grid",
      name: "Grid",
    },
  ],
  Date: [
    {
      label: "Date",
      name: "Date",
    },
    {
      label: "Date & Time",
      name: "DateTime",
    },
  ],
  ModuleForm: [
    {
      label: "Module",
      name: "Module",
    },
    {
      label: "Form",
      name: "Form",
    },
    {
      label: "Field",
      name: "Field",
    },
  ],
  TableReference: [
    {
      label: "Table",
      name: "Table",
    },
    {
      label: "Time Line",
      name: "TimeLine",
    },
    {
      label: "Calendar",
      name: "Calendar",
    },
  ],
};
export const catalogVariants = {
  Number: [
    {
      label: "Non Decimal",
      name: "Int",
    },
    {
      label: "Decimal",
      name: "Float",
    },
  ],
  DropDown: [
    {
      label: "Single Value",
      name: "Single",
    },
    {
      label: "Multiple Values",
      name: "Multiple",
    },
  ],
  TextArea: [
    {
      label: "Plain Text",
      name: "PlainText",
    },
    {
      label: "Rich Text",
      name: "RichText",
    },
  ],
  Reference: [
    {
      label: "Dropdown",
      name: "Dropdown",
    },
    {
      label: "Grid",
      name: "Grid",
    },
  ],
  Date: [
    {
      label: "Date",
      name: "Date",
    },
    {
      label: "Date & Time",
      name: "DateTime",
    },
  ],
  ModuleForm: [
    {
      label: "Module",
      name: "Module",
    },
    {
      label: "Form",
      name: "Form",
    },
    {
      label: "Field",
      name: "Field",
    },
  ],
  Radio: [
    {
      label: "Image",
      name: "Image",
    },
  ],
};
export const catalogType = [
  {
    label: "Document Type",
    value: "1",
  },
  {
    label: "Request",
    value: "2",
  },
];
